"""Cross-language compatibility tests for wlearn.nn.

Loads bundles generated by JS @wlearn/nn, verifies predictions match
within tolerance (atol=1e-5).
"""

import json
import pathlib

import numpy as np
import pytest

from wlearn.nn import MLPClassifier, MLPRegressor
from wlearn.bundle import decode_bundle

FIXTURES = pathlib.Path(__file__).resolve().parents[2] / 'fixtures' / 'nn'


def _skip_if_no_fixtures():
    if not FIXTURES.exists():
        pytest.skip('NN fixtures not generated (run: node packages/nn/test/test_cross_lang.js)')


class TestClassifierCompat:
    def test_load_js_bundle(self):
        _skip_if_no_fixtures()
        bundle_path = FIXTURES / 'mlp_classifier.wlrn'
        sidecar_path = FIXTURES / 'mlp_classifier.json'

        bundle_bytes = bundle_path.read_bytes()
        sidecar = json.loads(sidecar_path.read_text())

        manifest, toc, blobs = decode_bundle(bundle_bytes)
        assert manifest['typeId'] == 'wlearn.nn.mlp.classifier@1'

        model = MLPClassifier._from_bundle(manifest, toc, blobs)
        assert model.is_fitted

        X = np.array(sidecar['X'], dtype=np.float32)
        expected_preds = np.array(sidecar['predictions'], dtype=np.float64)
        expected_proba = np.array(sidecar['probabilities'], dtype=np.float64)

        # Verify predictions match
        preds = model.predict(X)
        np.testing.assert_array_equal(
            preds, expected_preds,
            err_msg='Classifier predictions differ from JS')

        # Verify probabilities match
        proba = model.predict_proba(X)
        np.testing.assert_allclose(
            proba, expected_proba, atol=1e-5,
            err_msg='Classifier probabilities differ from JS')

        # Verify metadata
        assert model._nr_class == sidecar['nrClass']
        np.testing.assert_array_equal(
            model.classes, np.array(sidecar['classes'], dtype=np.int32))

        model.dispose()

    def test_py_save_matches_js_predictions(self):
        """Python saves, reloads, predictions still match JS."""
        _skip_if_no_fixtures()
        bundle_path = FIXTURES / 'mlp_classifier.wlrn'
        sidecar_path = FIXTURES / 'mlp_classifier.json'

        bundle_bytes = bundle_path.read_bytes()
        sidecar = json.loads(sidecar_path.read_text())

        manifest, toc, blobs = decode_bundle(bundle_bytes)
        model = MLPClassifier._from_bundle(manifest, toc, blobs)

        # Re-save and reload
        resaved = model.save()
        manifest2, toc2, blobs2 = decode_bundle(resaved)
        model2 = MLPClassifier._from_bundle(manifest2, toc2, blobs2)

        X = np.array(sidecar['X'], dtype=np.float32)
        expected_preds = np.array(sidecar['predictions'], dtype=np.float64)

        preds2 = model2.predict(X)
        np.testing.assert_array_equal(
            preds2, expected_preds,
            err_msg='Predictions after Py save/load differ from JS')

        model.dispose()
        model2.dispose()


class TestRegressorCompat:
    def test_load_js_bundle(self):
        _skip_if_no_fixtures()
        bundle_path = FIXTURES / 'mlp_regressor.wlrn'
        sidecar_path = FIXTURES / 'mlp_regressor.json'

        bundle_bytes = bundle_path.read_bytes()
        sidecar = json.loads(sidecar_path.read_text())

        manifest, toc, blobs = decode_bundle(bundle_bytes)
        assert manifest['typeId'] == 'wlearn.nn.mlp.regressor@1'

        model = MLPRegressor._from_bundle(manifest, toc, blobs)
        assert model.is_fitted

        X = np.array(sidecar['X'], dtype=np.float32)
        expected_preds = np.array(sidecar['predictions'], dtype=np.float64)

        preds = model.predict(X)
        np.testing.assert_allclose(
            preds, expected_preds, atol=1e-5,
            err_msg='Regressor predictions differ from JS')

        model.dispose()

    def test_py_save_matches_js_predictions(self):
        """Python saves, reloads, predictions still match JS."""
        _skip_if_no_fixtures()
        bundle_path = FIXTURES / 'mlp_regressor.wlrn'
        sidecar_path = FIXTURES / 'mlp_regressor.json'

        bundle_bytes = bundle_path.read_bytes()
        sidecar = json.loads(sidecar_path.read_text())

        manifest, toc, blobs = decode_bundle(bundle_bytes)
        model = MLPRegressor._from_bundle(manifest, toc, blobs)

        resaved = model.save()
        manifest2, toc2, blobs2 = decode_bundle(resaved)
        model2 = MLPRegressor._from_bundle(manifest2, toc2, blobs2)

        X = np.array(sidecar['X'], dtype=np.float32)
        expected_preds = np.array(sidecar['predictions'], dtype=np.float64)

        preds2 = model2.predict(X)
        np.testing.assert_allclose(
            preds2, expected_preds, atol=1e-5,
            err_msg='Predictions after Py save/load differ from JS')

        model.dispose()
        model2.dispose()
